MoreJSEvents.registerPotionBrewing((event) => {
  /**
   * Removes all potions where an awkward potion is used as theb base potion ingredient.
   * 1. Argument: The input potion id to filter.
   * 2. Argument: The ingredient to filter.
   * 3. Argument: The result potion id to filter.
   * Passing `null` counts as a wildcard.
   */
  event.removeByPotion(null, 'minecraft:popped_chorus_fruit', null);
});

const tabs = [
  'actuallyadditions:tab',
  'advanced_ae:tab',
  // 'advancednetherite:tab',
  // 'ae2:facades',
  // 'ae2:main',
  'ae2additions:main',
  'ae2insertexportcard:ae2insertexportcard',
  'ae2wtlib:main',
  // 'aeinfinitybooster:aeinfinitybooster',
  // 'aether:armor_and_accessories',
  // 'aether:building_blocks',
  // 'aether:dungeon_blocks',
  // 'aether:equipment_and_utilities',
  // 'aether:food_and_drinks',
  // 'aether:functional_blocks',
  // 'aether:ingredients',
  // 'aether:natural_blocks',
  // 'aether:redstone_blocks',
  // 'aether:spawn_eggs',
  // 'alchemistry:machine_tab',
  // 'allthemodium:creative_tab',
  // 'alltheores:creative_tab',
  // 'alltheores:creative_tab_mek',
  // 'apotheosis:ench',
  // 'appflux:tab_main',
  // 'appmek:main',
  // 'armorplus:blocks',
  // 'armorplus:core',
  // 'armorplus:extra',
  // 'armorplus:items',
  // 'avaritia:avaritiatab',
  // 'better_angel_ring:better_angel_ring',
  // 'bhc:bhc_tab',
  'bigger_ae2:bigger_ae2',
  // 'bigreactors:tab.general',
  // 'bigreactors:tab.reactor',
  // 'bigreactors:tab.turbine',
  'bloodmagic:bloodmagic',
  'bloodmagic:bloodmagic_upgrades',
  // 'born_in_chaos_v1:block_borin_chaos',
  // 'born_in_chaos_v1:bornin_chaos_customization',
  // 'born_in_chaos_v1:bornin_chaos_items',
  // 'born_in_chaos_v1:bornin_chaos_mobs',
  // 'born_in_chaos_v1:debugging_bornin_chaos',
  // 'born_in_chaos_v1:weapons_bornin_chaos',
  // 'bosses_of_mass_destruction:bosses_of_mass_destruction',
  // 'botania:botania',
  // 'botanicalmachinery:tab',
  // 'botanypots:creative_tab',
  // 'botanypotstiers:creative_tab',
  // 'buildinggadgets2:buildinggadgets2',
  // 'bygonenether:bygonenether',
  // 'cabletiers:cabletiers',
  // 'cataclysm:cataclysm_block',
  // 'cataclysm:cataclysm_item',
  // 'cb_microblock:microblocks',
  // 'chancecubes:tab',
  // 'chemlib:compound_tab',
  // 'chemlib:element_tab',
  // 'chemlib:metals_tab',
  // 'chemlib:misc_tab',
  // 'chipped:main',
  // 'chisel_chipped_integration:chisel',
  // 'common_ore_library:common_ore_library',
  // 'compacter:main',
  // 'compactmachines:main',
  // 'compressium:compressium',
  // 'cursedearth:cursed_earth',
  // 'cyclic:items',
  // 'cyclic:tab',
  // 'dankstorage:tab',
  // 'darkutils:creative_tab',
  // 'dimdoors:decay',
  // 'dimdoors:dimensional_doors',
  // 'dimensionalpocketsii:dimensionalpocketsii.blocks',
  // 'dimensionalpocketsii:dimensionalpocketsii.items',
  // 'dimensionalpocketsii:dimensionalpocketsii.tools',
  // 'draconicadditions:items',
  // 'draconicevolution:blocks',
  // 'draconicevolution:items',
  // 'draconicevolution:modules',
  // 'elevatorid:elevators_tab',
  // 'enderchests:default',
  // 'enderio:blocks',
  // 'enderio:conduits',
  // 'enderio:gear',
  // 'enderio:machines',
  // 'enderio:main',
  // 'enderio:souls',
  // 'endertanks:default',
  // 'everlastingabilities:default',
  // 'exdeorum:main',
  // 'expatternprovider:tab_main',
  // 'extendedcrafting:creative_tab',
  'extradisks:general',
  'extrastorage:main_tab',
  // 'fluxnetworks:tab',
  // 'ftbfiltersystem:default',
  // 'ftbquests:default',
  // 'functionalstorage:main',
  // 'gardens_of_the_dead:main',
  // 'gateways:tab',
  // 'hammerlib:root',
  // 'hostilenetworks:tab',
  // 'industrialforegoing:ag_hus',
  // 'industrialforegoing:core',
  // 'industrialforegoing:generator',
  // 'industrialforegoing:misc',
  // 'industrialforegoing:resource_production',
  // 'industrialforegoing:tool',
  // 'industrialforegoing:transport',
  // 'industrialforegoingsouls:main',
  // 'integratedcrafting:default',
  // 'integrateddynamics:default',
  // 'integratedterminals:default',
  // 'integratedtunnels:default',
  // 'ironjetpacks:creative_tab',
  // 'itemfilters:default',
  // 'kubejs:tab',
  // 'laserio:laserio',
  // 'matc:matc',
  'megacells:tab',
  // 'mekanism:mekanism',
  // 'mekanismadditions:mekanismadditions',
  // 'mekanismgenerators:mekanismgenerators',
  // 'mekanismtools:mekanismtools',
  // 'merequester:tab',
  // 'mifa:addons',
  // 'minecraft:building_blocks',
  // 'minecraft:colored_blocks',
  // 'minecraft:combat',
  // 'minecraft:food_and_drinks',
  // 'minecraft:functional_blocks',
  // 'minecraft:hotbar',
  // 'minecraft:ingredients',
  // 'minecraft:inventory',
  // 'minecraft:natural_blocks',
  // 'minecraft:op_blocks',
  // 'minecraft:redstone_blocks',
  // 'minecraft:search',
  // 'minecraft:spawn_eggs',
  // 'minecraft:tools_and_utilities',
  // 'mm:mm',
  // 'mob_grinding_utils:tab',
  // 'modonomicon:modonomicon',
  // 'modularrouters:default',
  // 'mutantmonsters:main',
  // 'mysticaladaptations:creative_tab',
  // 'mysticalagradditions:creative_tab',
  // 'mysticalagriculture:creative_tab',
  // 'mysticalexpansion:mystical_expansion',
  // 'nuclearcraft:fission_reactor',
  // 'nuclearcraft:fusion_reactor',
  // 'nuclearcraft:kugelblitz',
  // 'nuclearcraft:nc_blocks',
  // 'nuclearcraft:nc_fluids',
  // 'nuclearcraft:nc_items',
  // 'nuclearcraft:nc_parts',
  // 'nuclearcraft:turbine',
  // 'obtrophies:trophies',
  'occultism:occultism',
  // 'outer_end:outer_end_tab',
  // 'packagedauto:tab',
  // 'packagedexcrafting:tab',
  // 'packagedexexcrafting:tab',
  // 'phosphophyllite:creative_tab',
  // 'pickletweaks:creative_tab',
  // 'pipez:pipez',
  // 'pneumaticcraft:default',
  // 'powah:tab',
  // 'projecte:projecte',
  // 'projectexpansion:projectexpansion',
  // 'projectextended:projectextended',
  // 'quartz:creative_tab',
  // 'rebornstorage:creative_tab',
  'redstone_arsenal:redstone_arsenal',
  'refinedstorage:general',
  'refinedstorageaddons:general',
  // 'rftoolsbase:rftoolsbase',
  // 'rftoolsbase:rftoolsbuilder',
  // 'rftoolscontrol:rftoolscontrol',
  'rftoolsdim:rftoolsdim',
  // 'rftoolspower:rftoolspower',
  // 'rftoolsstorage:rftoolsstorage',
  // 'rftoolsutility:rftoolsutility',
  // 'rsinfinitybooster:aeinfinitybooster',
  // 'rsinsertexportupgrade:rsinsertexportupgrade',
  // 'rsrequestify:rsrequestify',
  // 'runelic:creative_tab',
  // 'silentgems:tab',
  // 'simplemagnets:simplemagnets',
  // 'solarflux:root',
  // 'sophisticatedbackpacks:main',
  // 'structurecompass:tab',
  // 'tcintegrations:tcintegrations.items',
  // 'tconstruct:fluids',
  // 'tconstruct:general',
  // 'tconstruct:smeltery',
  // 'tconstruct:tables',
  // 'tconstruct:tool_parts',
  // 'tconstruct:tools',
  // 'tconstruct:world',
  // 'telepastries:tab',
  'thermal:thermal.blocks',
  'thermal:thermal.devices',
  'thermal:thermal.foods',
  'thermal:thermal.items',
  'thermal:thermal.tools',
  'thermal_extra:augments',
  'thermal_extra:machines',
  'thermal_extra:resources',
  'thermal_processing:thermal_processing',
  'thermalendergy:base',
  // 'torchmaster:creative_tab',
  // 'twilightforest:blocks',
  // 'twilightforest:equipment',
  // 'twilightforest:items',
  // 'undead_revamp2:theundeadcreative',
  // 'undergarden:undergarden_group',
  // 'universalgrid:universalgrid',
  'valkyrielib:main',
  // 'voidminers:items',
  // 'waystones:waystones',
  // 'xnet:xnet'
];

tabs.forEach((tab) => {
  StartupEvents.modifyCreativeTab(tab, (event) => {
    event.remove(/.*/);
  });
});
