// ClientEvents.lang("en_us", e => {
//     e.renameItem('kubejs:microverse/microminer_t1', 'Mircominer T1')
//     e.renameItem('kubejs:microverse/microminer_t2', 'Mircominer T2')
//     e.renameItem('kubejs:microverse/microminer_t3', 'Mircominer T3')
//     e.renameItem('kubejs:microverse/microminer_t4', 'Mircominer T4')
//     e.renameItem('kubejs:microverse/microminer_t4half', 'Mircominer T4 MobKiller')
//     e.renameItem('kubejs:microverse/microminer_t5', 'Mircominer T5')
//     e.renameItem('kubejs:microverse/microminer_t6', 'Mircominer T6')
//     e.renameItem('kubejs:microverse/microminer_t7', 'Mircominer T7')
//     e.renameItem('kubejs:microverse/microminer_t8', 'Mircominer T8')
//     e.renameItem('kubejs:microverse/microminer_t8half', 'Mircominer T8 MobDestroyer')
//     e.renameItem('kubejs:microverse/microminer_t9', 'Mircominer T9')
//     e.renameItem('kubejs:microverse/microminer_t10', 'Mircominer T10')
//     e.renameItem('kubejs:microverse/microminer_t11', 'Mircominer T11')
//     e.renameItem('kubejs:microverse/microminer_t12', 'Mircominer T12')
//     console.log("Renaming finished")
//     })