
#Asgard configuration
[asgard]
	#Range: > 0
	asgardManaStorage = 1000000
	#Range: > 0
	asgardManaGenerationPerTick = 1000000
	#Range: > 0
	asgardLinkationRadius = 32
	#Range: > 0
	asgardIIManaStorage = 10000000
	#Range: > 0
	asgardIIManaGenerationPerTick = 2500000
	#Range: > 0
	asgardIILinkationRadius = 64
	#Range: > 0
	asgardIIIManaStorage = 100000000
	#Range: > 0
	asgardIIIManaGenerationPerTick = 10000000
	#Range: > 0
	asgardIIILinkationRadius = 128

