
#Evolved Mekanism Extras Tank Capacity Config
[tank]
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	AbsoluteOverclockedFactories = 30240
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	SupremeQuantumFactories = 41160
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	CosmicDenseFactories = 53760
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	InfiniteMultiversalFactories = 68040
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	AbsoluteOverclockedInfusingFactory = 144000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	SupremeQuantumInfusingFactory = 196000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	CosmicDenseInfusingFactory = 256000
	#Chemical tank capacity (mB).
	#Range: 1 ~ 9223372036854775807
	InfiniteMultiversalInfusingFactory = 324000

